[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.19.0"

[[constraint]]
  branch = "master"
  name = "github.com/antzucaro/matchr"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.40"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/chanzuckerberg/go-misc"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.2.0"

[[constraint]]
  name = "github.com/hashicorp/go-getter"
  version = "1.3.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.12.0"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/segmentio/go-prompt"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.29.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
